apiVersion: v1
kind: Service
metadata:
  name: javaweb-service
spec:
  selector:
    app.kubernetes.io/name: javaweb
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  externalIPs:
    -  10.0.2.15
